# Labels based on file changes
documentation:
  - '**/*.md' # Matches all markdown files

ci/cd:
  - '.github/**' # Matches all files in the .github directory

dependencies:
  - 'package.json'
  - 'package-lock.json'

# Labels based on branch names
feature:
  - head-branch: ['^feature/', 'feature'] # Matches branches starting with 'feature' or 'feature/'

bugfix:
  - head-branch: ['^fix/', 'bug'] # Matches branches starting with 'fix/' or 'bug'
