# Labels based on file changes
documentation:
  - paths:
      - '**/*.md'

ci/cd:
  - paths:
      - '.github/**'

dependencies:
  - paths:
      - 'package.json'
      - 'package-lock.json'

# Labels based on branch names
feature:
  - head-branch:
      - '^feature/'
      - 'feature'

bugfix:
  - head-branch:
      - '^fix/'
      - 'bug'
